#%RAML 0.8
title: Rock, Paper, Scissor API
mediaType: application/json

schemas:
  - user.json: !include schema/user.json
  - round.json: !include schema/round.json
  - error.json: !include schema/error.json
  - stats.json: !include schema/stats.json

/user:
  post:
    responses:
      200:
        body:
          schema: user.json

/round:
  /user/{userId}:
    uriParameters:
      userId:
        type: string
        description: User that owned the round.
    post:
      responses:
        200:
          body:
            schema: round.json
        400:
          body:
            schema: error.json
    delete:
      responses:
        200:
        400:
          body:
            schema: error.json
/stats:
  get:
    responses:
      200:
        body:
          schema: stats.json


